language: node_js
node_js:
  - 10.8.0
before_install:
  - "if [ \"$TRAVIS_EVENT_TYPE\" !=\"cron\" ] && echo \"$TRAVIS_COMMIT_MESSAGE\" | grep -F -q \"Auto-commit\"; then echo \"Last commit was made by Travis, exiting...\" && exit 0; fi"i
  - rvm install 2.4.1
install:
  - bundle install
script:
  - ./.scripts/update.sh
before_deploy:
  - git status
deploy:
  provider: script
  skip_cleanup: true
  script: 
    - ./.scripts/deploy.sh
  on:
    branch: master
