name: James Fenn
author: James Fenn
email: "me@jfenn.me"
bio: "Enjoys writing software on loud keyboards. Starts too many projects. Consumes food."
description: "Writer of bad puns and slightly better software. This website contains information about my adventures in programming, current projects, and me."
icon: "/images/me.jpg"
image: "/images/headers/snowytrees.jpg"

contact:
  - name: "Discord"
    icon: "group"
    url: "https://discord.jfenn.me/"
  - name: "Telegram"
    icon: "chat"
    url: "https://t.me/joinchat/JV--FRZrSf-NJqeE0OGKXg"

url: "https://jfenn.me"
domainurl: "https://jfenn.me"
baseurl: "/"

collections:
    types:
        output: false
    links:
        output: true
    people:
        output: false
    orgs:
        output: false
    projects:
        output: true
        permalink: /projects/:title/
    posts:
        output: true
        permalink: /:categories/:year-:month-:day-:title/
    categories:
        output: true
        permalink: /:slug/
    tags:
        output: true

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package-install.lock
  - package-lock.json
  - package.json

include:
  - .scripts
  - .travis.yml

sass:
    sass_dir: ./css

plugins:
  - jekyll-sitemap
